import React, { useEffect, useRef } from "react";
import { MotiView, MotiText } from "moti";
import { useFonts, HankenGrotesk_400Regular } from "@expo-google-fonts/hanken-grotesk";
import * as Font from "expo-font";
import { FlatList, Dimensions, LayoutChangeEvent, ListRenderItemInfo, Animated } from "react-native";

type Props = {};

const Suggestions = (props: Props) => {
  const [fontsLoaded] = useFonts({
    HankenGrotesk_400Regular,
  });

  //const screenWidth = useRef(Dimensions.get("window").width).current;

  const searchQuestions = [
    "🍝 How to cook pasta",
    "🏋️‍♂️ Best fitness apps",
    "💻 Learn coding online",
    "🍲 Quick dinner recipes",
    "✈️ Top travel destinations",
    "📝 Create a blog",
    "📚 Effective study techniques",
    "🌿 Indoor plant care",
    "🛋️ DIY home decor ideas",
    "🥑 Healthy breakfast recipes",
    "🧘 Improve focus tips",
    "💰 Financial saving hacks",
    "🗣️ Learn a new language",
    "💪 Best workout routines",
    "🧘‍♂️ Mindfulness meditation",
    "📖 Book recommendations",
    "🎥 Start a YouTube channel",
    "🔧 How to fix leaks",
    "🎙️ Podcast recommendations",
    "🌿 Reduce stress naturally",
    "🗂️ Stay organized tips",
    "🎉 Quick dinner party ideas",
    "🏡 Work from home tips",
    "🪴 Grow indoor plants",
    "🥩 Perfect steak recipe",
    "🥗 Healthy lunch ideas",
    "⌛ Time management tips",
    "🏃‍♀️ Start a fitness routine",
    "✍️ Creative writing inspiration",
    "📱 Productivity apps",
    "🍕 Make homemade pizza",
    "🌅 Morning routine ideas",
    "🧠 Focus improvement tips",
    "🚗 Change a car tire",
    "🌬️ Breathing exercises",
    "🎥 YouTube channel guide",
    "💧 Stay hydrated ways",
    "🥤 Healthy smoothies recipes",
    "💻 Learn coding basics",
    "🧴 DIY skincare routine",
    "🌟 Favorite inspirational quotes",
    "🎯 Achievable goal setting",
    "👗 2022 fashion trends",
    "🚶‍♂️ Improve posture exercises",
    "🍴 Kitchen gadgets must-haves",
    "🌿 Eco-friendly living tips",
    "🧘‍♂️ Meditation for beginners",
    "🍲 Budget-friendly recipes",
    "😊 Stay positive daily",
    "🏋️‍♂️ Go-to workout routine",
    "🎨 Create digital art guide",
    "🥦 Meal prep ideas healthy",
    "🚲 Fix a bicycle tips",
    "🎥 Watch documentaries list",
    "🎙️ Start a podcast steps",
    "🛀 Unwind after work",
    "🤖 Favorite tech gadgets",
    "🌎 Make a difference ideas",
    "🍳 Easy and quick recipes",
    "😴 Improve sleep quality",
    "⛰️ Outdoor activities list",
    "☕ Morning beverage choices",
    "📚 Effective studying tips",
    "🍨 Make homemade ice cream",
    "🌞 Morning routine creation",
    "🍿 Go-to snacks preferences",
    "🚗 Plan a weekend getaway",
    "🏋️‍♀️ Favorite workout session",
    "🙏 Practice gratitude daily",
    "🌟 Inspirational quotes list",
    "📈 Start a small business",
    "✈️ Travel hacks pro tips",
    "🧥 Organize a closet guide",
    "📖 Self-help books to read",
    "🥤 Delicious smoothie recipes",
    "🌱 Plant-based cooking tricks",
    "📚 Choose a good book tips",
    "🍜 Homemade ramen recipe",
  "🚴‍♀️ Bike maintenance tips",
  "🎮 Best video games to play",
  "🎸 Learn to play guitar chords",
  "🚤 Plan a boating adventure",
  "👩‍🍳 Master cooking techniques",
  "🧘‍♀️ Yoga poses for relaxation",
  "🖥️ Start a coding project",
  "🏞️ Explore national parks",
  "🌌 Stargazing tips",
  "📸 Photography composition",
  "🎤 Singing exercises for beginners",
  "👩‍🎨 Acrylic painting tutorial",
  "🍹 Refreshing summer drinks",
  "📚 Classic literature recommendations",
  "🌻 Gardening for beginners",
  "🎭 Acting tips for amateurs",
  "💡 Home improvement ideas",
  "🕰️ Antique hunting guide",
  "🌍 Volunteer for a cause",
  "🏰 Historical places to visit",
  "🕹️ Retro gaming collection",
  "🏖️ Beach picnic essentials",
  "🧁 Baking delicious cupcakes",
  "🚀 Space exploration documentaries",
  "🏠 Feng Shui for home harmony",
  "🎓 Online learning platforms",
  "🎧 Discover new music genres",
  "🔥 BBQ grilling techniques",
  "🚁 Helicopter tour experience",
  "🌿 Natural remedies for allergies",
  "🛹 Skateboarding tricks",
  "👾 Create your own video game",
  "📝 Journaling prompts",
  "🍎 Apple orchard visit",
  "🔍 Mystery novels reading list",
  "🏞️ Camping under the stars",
  "🎉 Celebrate small victories",
  "🌈 DIY rainbow crafts",
  "🚲 Mountain biking trails",
  "🎧 Podcasts for personal growth",
  "🍣 Sushi making at home",
  "🎭 Improv comedy techniques",
  "🧘‍♂️ Mindful breathing exercises",
  "🌅 Sunset photography tips",
  "👩‍💻 Virtual team building activities",
  "🚗 Road trip essentials",
  "🌸 Floral arrangement ideas",
  "🛏️ Feng Shui bedroom layout",
  "🏕️ Glamping experience",
  "🍷 Wine tasting at home",
  "🎙️ Audiobooks for long drives",
  "🎨 DIY tie-dye projects",
  "📸 Capture the perfect selfie",
  "📚 Must-read business books",
  "🎯 Archery basics",
  "🍀 Luck-enhancing rituals",
  "🎹 Learn piano online",
  "🍕 Pizza dough from scratch",
  "🚁 Hot air balloon ride",
  "📆 Plan a monthly goal calendar",
  "🏠 Declutter your living space",
  "🌧️ Indoor rainy day activities",
  "🍜 Explore different cuisines",
  "📰 Stay informed with news",
  "🎙️ Stand-up comedy watching",
  "🚴‍♂️ Bikepacking adventure",
  "🎸 Guitar solo techniques",
  "📷 Master smartphone photography",
  "📝 Poetry writing inspiration",
  "🍩 Homemade donut recipes",
  "🚣‍♂️ Kayaking in scenic spots",
  "🎤 Karaoke night at home",
  "📚 Historical fiction novels",
  "🧘‍♀️ Guided meditation sessions",
  "🚲 Explore bike trails",
  "🌮 Taco Tuesday ideas",
  "🛁 DIY spa day at home",
  "🍛 Indian cuisine cooking class",
  "🌍 Best travel destinations 2024",
  "🎸 Learn guitar basics",
  "🍕 Top-rated pizza places near me",
  "👔 How to tie a tie",
  "🌦️ Weather forecast tomorrow",
  "🎨 DIY home decor ideas",
  "📚 Must-read books 2024",
  "💪 Quick workout routines",
  "🥗 Healthy breakfast recipes",
  "🎬 Latest movie releases",
  "🎵 Discover new music genres",
  "🌱 How to plant a garden",
  "👩‍🍳 Easy dinner recipes",
  "📺 Popular Netflix series",
  "📷 Photography tips for beginners",
  "🧘‍♂️ Meditation techniques",
  "📰 Current technology trends",
  "🇪🇸 Learn Spanish online",
  "💄 DIY skincare routine",
  "🔬 Interesting science facts",
  "💻 Best budget laptops 2024",
  "💑 Online dating tips",
  "😻 Cute cat videos on YouTube",
  "🏋️‍♀️ Outdoor workout ideas",
  "🎨 Easy drawing tutorials",
  "🗺️ Historical events timeline",
  "🍔 Unique burger recipes",
  "🎧 Wireless earbuds reviews",
  "🚴‍♂️ Bike trails near me",
  "🎭 Virtual art classes",
  "🏞️ National parks to visit",
  "📝 Creative writing prompts",
  "🚗 Electric cars pros and cons",
  "🍦 Homemade ice cream recipes",
  "👾 Latest video games 2024",
  "🚲 Cycling for fitness",
  "🛌 Improve sleep quality tips",
  "🎭 Broadway shows schedule",
  "🎉 Party planning ideas",
  "🐶 Dog training techniques",
  "👨‍🍳 Cooking classes online",
  "🚀 Space exploration news",
  "🚴‍♀️ Mountain biking trails",
  "📱 Smartphone photography tricks",
  "🍹 Summer cocktail recipes",
  "🎤 Karaoke songs for beginners",
  "📚 Educational podcasts list",
  "🕹️ Retro video games collection",
  "🍲 One-pot dinner recipes",
  "📸 Instagram photo ideas",
  "🏰 Virtual museum tours",
  "🧁 Baking without an oven recipes",
  "🕵️‍♂️ Mystery novels recommendations",
  "🚴‍♂️ Cycling safety tips",
  "🎨 Art therapy benefits",
  "👗 Sustainable fashion brands",
  "🌌 Stargazing tips for beginners",
  "🥑 Vegan meal prep ideas",
  "🎓 Online courses discounts",
  "🌸 Indoor plants care guide",
  "🚗 Road trip essentials checklist",
  "🧘‍♀️ Mindfulness meditation apps",
  "🎬 Classic movies to watch",
  "🍇 Wine tasting at home",
  "🚁 Helicopter tours near me",
  "🎶 Music festivals 2024",
  "🥢 Quick Asian cuisine recipes",
  "📖 Book club reading list",
  "🏞️ Scenic hiking trails",
  "📚 Self-help books recommendations",
  "🖌️ Watercolor painting techniques",
  "🍛 Authentic ethnic recipes",
  "🎲 Board games for family night",
  "🌳 Urban gardening tips",
  "🎭 Improv comedy classes online",
  "🚤 Kayaking adventures",
  "🚁 Hot air balloon rides experience",
  "🧘‍♂️ Yoga poses for relaxation",
  "🚴‍♀️ Cycling events near me",
  "🎨 DIY craft projects",
  "📱 Smartphone productivity apps",
  "📚 Autobiography books list",
  "🥤 Healthy smoothie recipes",
  "🧗‍♀️ Rock climbing basics",
  "🚗 Electric car charging stations map",
  "🕹️ Retro arcade games history",
  "🎻 Learn to play the violin",
  "🌌 Astrophotography tips",
  "🏰 Historical castles to visit",
  "🎬 Behind-the-scenes movie facts",
  "🍔 Gourmet burger recipes",
  "👾 Virtual reality games 2024",
  "🚤 Sailing lessons for beginners",
  "🕊️ Mindfulness and meditation benefits",
  "🌺 Flower arranging tutorials",
  "🍲 Easy soup recipes",
  "📸 Nature photography techniques",
  "🎨 Pottery making at home",
  "🎶 Jazz music history",
  "🚴‍♂️ BMX biking tricks",
  "🍹 Mocktail recipes for parties",
  "🎭 Stand-up comedy specials",
  "📚 Mystery book series",
  "🚀 SpaceX latest achievements",
  "🍛 Traditional family recipes",
  "👩‍🍳 Culinary school online",
  "🎨 Abstract painting techniques",
  "🍦 Vegan ice cream recipes",
  "🚲 Bike maintenance tips",
  "🎤 Open mic night venues",
  "🍇 Wine and cheese pairings",
  "🏞️ Hidden gems in nature",
  "📖 Historical fiction novels",
  "📱 Mobile photography editing apps",
  "🎬 Cult classic movies list",
  "🧘‍♀️ Guided meditation podcasts",
  "🥑 Plant-based protein sources",
  "🎓 Online language courses",
  "🌸 DIY flower arrangements",
  "🚗 Classic car restoration tips",
  "🎭 Improv comedy shows near me",
  "🛤️ Long-distance hiking trails",
  "📚 Best-selling novels 2024",
  "🍲 International cuisine recipes",
  "📸 Landscape photography tips",
  "🎨 DIY jewelry making ideas",
  "🎶 Music genres timeline",
  "🚴‍♀️ Women's cycling groups",
  "📱 Smartphone camera accessories",
  "🍹 Tropical cocktail recipes",
  "🎤 Comedy open mic sign-up",
  "🚀 NASA's latest discoveries",
  "🍛 Ethnic comfort food recipes",
  "👨‍🍳 Online cooking classes free",
  "🎨 Mixed media art projects",
  "🍦 Dairy-free ice cream recipes",
  "🚲 Bike trails for beginners",
  "🎤 Improv comedy workshops",
  "🍇 Wine tasting event calendar",
  "🏞️ Natural wonders to explore",
  "📖 Historical non-fiction books",
  "📱 Mobile photography tips",
  "🎬 Classic Hollywood movies",
  "🧘‍♂️ Mindful breathing exercises",
  "🥑 Vegan dessert recipes",
  "🎓 Language learning apps reviews",
  "🌸 Indoor plants for beginners",
  "🚗 Road trip planning tips",
  "📚 Self-help audiobooks list",
  "🖌️ Acrylic painting techniques",
  "🍜 Ramen noodle recipes",
  "🎲 Family board game night ideas",
  "🌳 Urban gardening hacks",
  "🎭 Improv comedy events calendar",
  "🚤 Sailing adventure destinations",
  "🕊️ Mindfulness meditation techniques",
  "🌺 DIY flower bouquets",
  "🍲 Homemade soup recipes",
  "📸 Macro photography tips",
  "🎨 Pottery wheel throwing techniques",
  "🎶 Jazz music evolution",
  "🚴‍♂️ Mountain biking trails map",
  "🍹 Mocktail recipes for kids",
  "🎭 Stand-up comedy specials list",
  "📚 Mystery thriller books",
  "🚀 Space exploration timeline",
  "🍛 Family dinner recipes",
  "👩‍🍳 Culinary school reviews online",
  "🎨 Abstract art painting ideas",
  "🍦 Vegan ice cream flavors",
  "🚲 Bike maintenance checklist",
  "🎤 Open mic night performances",
  "🍇 Wine and chocolate pairings",
  "🏞️ Hidden nature spots",
  "📖 Historical fiction audiobooks",
  "📱 Mobile photography editing tools",
  "🎬 Cult classic movies trivia",
  "🧘‍♀️ Guided mindfulness meditation",
  "🥑 Plant-based protein recipes",
  "🎓 Online language courses discounts",
  "🌸 DIY flower pot ideas",
  "🚗 Classic car restoration projects",
  "🎭 Improv comedy show tickets",
  "🛤️ Long-distance hiking trails guide",
  "📚 Best-selling novels of all time",
  "🍲 International comfort food recipes",
  "📸 Landscape photography composition tips",
  "🎨 DIY jewelry making supplies",
  "🎶 Music genres history",
  "🚴‍♀️ Women's cycling events",
  "📱 Smartphone camera photography tips",
  "🍹 Tropical mocktail recipes",
  "🎤 Comedy open mic night sign-up",
  "🚀 NASA's latest discoveries",
  "🍛 Ethnic recipes collection",
  "👨‍🍳 Cooking classes beginners",
  "🎨 Mixed media art",
  "🍦 Dairy-free ice cream",
  "🚲 Bike trails beginners",
  "🎤 Improv comedy workshops",
  "🍇 Wine tasting events",
  "🏞️ Explore natural wonders",
  "📖 Best historical non-fiction",
  "📱 Mobile photography tips",
  "🎬 Classic Hollywood movies",
  "🧘‍♂️ Mindful breathing exercises",
  "🥑 Vegan dessert recipes",
  "🎓 Language learning apps",
  "🌸 Indoor plants beginners",
  "🚗 Road trip planning",
  "📚 Self-help audiobooks list",
  "🖌️ Acrylic painting techniques",
  "🍜 Ramen noodle recipes",
  "🎲 Family game night",
  "🌳 Urban gardening hacks",
  "🎭 Improv comedy events",
  "🚤 Sailing adventure destinations",
  "🕊️ Mindfulness meditation techniques",
  "🌺 DIY flower bouquets",
  "🍲 Homemade soup recipes",
  "📸 Macro photography tips",
  "🎨 Pottery wheel techniques",
  "🎶 Jazz music history",
  "🚴‍♂️ Mountain biking trails",
  "🍹 Mocktail recipes parties",
  "🎭 Stand-up comedy specials",
  "📚 Mystery thriller books",
  "🚀 Space exploration timeline",
  "🍛 Family dinner recipes",
  "👩‍🍳 Culinary school reviews",
  "🎨 Abstract art painting",
  "🍦 Vegan ice cream",
  "🚲 Bike maintenance checklist",
  "🎤 Open mic performances",
  "🍇 Wine chocolate pairings",
  "🏞️ Hidden nature spots",
  "📖 Historical fiction audiobooks",
  "📱 Mobile photography tools",
  "🎬 Cult classic movies",
  "🧘‍♀️ Guided mindfulness meditation",
  "🥑 Plant-based protein recipes",
  "🎓 Online language courses",
  "🌸 DIY flower pot",
  "🚗 Classic car restoration",
  "🎭 Improv comedy show",
  "🛤️ Long-distance hiking trails",
  "📚 Best-selling novels classics",
  "🍲 International comfort food",
  "📸 Landscape photography tips",
  "🎨 DIY jewelry making",
  "🎶 Music genres history"
  ];

  const flatListRef = useRef<FlatList<any> | null>(null);

  const searchQuestionsWithKeys = searchQuestions.map((question, index) => ({
    key: `${index}`,
    text: question,
  }));

  //const scrollX = useRef(new Animated.Value(0)).current;

  /*const measureTotalWidth = (event: LayoutChangeEvent) => {
    const { width } = event.nativeEvent.layout;
    console.log(`Total width of FlatList: ${width}`);
    return width; 
  };*/
  useEffect(() => {
    const loadFonts = async () => {
      await Font.loadAsync({
        HankenGrotesk_400Regular,
      });
    };

    const setupFonts = async () => {
      if (!fontsLoaded) {
        await loadFonts();
      }
    };

    setupFonts();

   /*const initialWidth = screenWidth * 3; 
    scrollX.setValue(-initialWidth);*/

  }, [fontsLoaded]);

  if (!fontsLoaded) {
    return null;
  }

  /*const onScroll = Animated.event([{ nativeEvent: { contentOffset: { x: scrollX } } }], {
    useNativeDriver: false,
  });*/

  const renderFlatList = (data: { key: string; text: string }[]) => (
    <FlatList
      ref={(ref) => {
        flatListRef.current = ref;
      }}
      horizontal
      showsHorizontalScrollIndicator={false}
      keyExtractor={(item) => item.key}
      data={data}
      renderItem={questionDisplay}
      scrollEventThrottle={16}
    />
  );

  const questionDisplay = ({ item }: ListRenderItemInfo<{ key: string; text: string }>) => (
    <MotiView className="h-10 items-center justify-center flex mr-3 pl-4 pr-4 bg-slate-100 rounded-md ml-3 -left-44" //set left for 44 temporarily
    >
      <MotiText className="text-gray-600 text-xl pt-0.5" style={{ fontFamily: "HankenGrotesk_400Regular" }}>
        {item.text}
      </MotiText>
    </MotiView>
  );

  return (
    <MotiView className="w-screen h-1/5 flex absolute top-40percent mt-8 items-center">
      {renderFlatList(searchQuestionsWithKeys.slice(0, 140))}
      {renderFlatList(searchQuestionsWithKeys.slice(141, 281))}
      {renderFlatList(searchQuestionsWithKeys.slice(282, 424))}
    </MotiView>
  );
};

export default Suggestions;